### ISSUE TITLE
[Requirement Package Version] cirq=0.8.2 is not compatible with 

### ISSUE THREAD

**Issue by JiahaoYao** [quantumlib/ReCirq#61]
Hi @mpharrigan, I met with the install error for the package. Here are the description of the error and my approach to getting around. 

```
Installed /home/ABC/anaconda3/envs/recirq/lib/python3.7/site-packages/recirq-0.1.dev0-py3.7.egg
Processing dependencies for recirq==0.1.dev0
Searching for cirq==0.8.2
Reading https://pypi.org/simple/cirq/
Downloading https://files.pythonhosted.org/packages/1e/5b/6f8cb54ea8c0041ad9c8e4ece07cb5ca9eb1c29de68e68795b4a40d90cc6/cirq-0.8.2-py3-none-any.whl#sha256=84c2ace7f6cb96b21e9265ea31a25c2fbc044ee79da30beb83fe3865e2cc05f8
Best match: cirq 0.8.2
Processing cirq-0.8.2-py3-none-any.whl
Installing cirq-0.8.2-py3-none-any.whl to /home/ABC/anaconda3/envs/recirq/lib/python3.7/site-packages
Adding cirq 0.8.2 to easy-install.pth file

Installed /home/ABC/anaconda3/envs/recirq/lib/python3.7/site-packages/cirq-0.8.2-py3.7.egg
error: cirq 0.8.2 is installed but cirq==0.8 is required by {'pytket-cirq'}
```

I think this is related to the [requirement.txt](https://github.com/quantumlib/ReCirq/blob/master/requirements.txt#L1). 

If it is changed to `cirq=0.8.0`, there is no such issue.

**Comment by mpharrigan** [comment]
It looks like this is because `pytket-cirq` (a 3rd party dependency) is pinned to version 0.8, but we actually applied a couple bug fixes (ironically around dependency management) that means we really want to be using 0.8.2. In an ideal world, the pyket folks would use a looser pin, i.e. `cirq~=0.8` so it wouldn't cause an unsatisfiable dependency.

I know it says error, but does it legitimately not work? As I understand it, `pip` is fairly forgiving and will proceed anyway

**Comment by JiahaoYao** [comment]
yes, you are right! Thanks so much for your reply! Hope pyket folks can fix that!
And I am closing #61.
